import React from 'react';
import s from "./Standards.module.css"
import g from "../../../globalStyles.module.css";
import {useTranslation} from "react-i18next";
import DownloadBtn from "./DownloadBtn";

function Standards() {
    const {t} = useTranslation()
    return (
        <section>
            <div className={g.sectionTitle}>
                <h2>{t("menu.resources.subMenu.item2")}</h2>
            </div>
            <div className={s.pdfBlock}>
                <div className={s.accounting}>
                    <h3>{t("pdfAcc.title")}</h3>
                    <DownloadBtn
                        code={t("pdfAcc.item1.code")}
                        text={t("pdfAcc.item1.text")}
                        link={"acc/IAS_1.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item2.code")}
                        text={t("pdfAcc.item2.text")}
                        link={"acc/IAS_2.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item3.code")}
                        text={t("pdfAcc.item3.text")}
                        link={"acc/IAS_7.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item4.code")}
                        text={t("pdfAcc.item4.text")}
                        link={"acc/IAS_8.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item5.code")}
                        text={t("pdfAcc.item5.text")}
                        link={"acc/IAS_10.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item6.code")}
                        text={t("pdfAcc.item6.text")}
                        link={"acc/IAS_12.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item7.code")}
                        text={t("pdfAcc.item7.text")}
                        link={"acc/IAS_16.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item8.code")}
                        text={t("pdfAcc.item8.text")}
                        link={"acc/IAS_19.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item9.code")}
                        text={t("pdfAcc.item9.text")}
                        link={"acc/IAS_20.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item10.code")}
                        text={t("pdfAcc.item10.text")}
                        link={"acc/IAS_21.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item11.code")}
                        text={t("pdfAcc.item11.text")}
                        link={"acc/IAS_23.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item12.code")}
                        text={t("pdfAcc.item12.text")}
                        link={"acc/IAS_24.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item13.code")}
                        text={t("pdfAcc.item13.text")}
                        link={"acc/IAS_26.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item14.code")}
                        text={t("pdfAcc.item14.text")}
                        link={"acc/IAS_27.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item15.code")}
                        text={t("pdfAcc.item15.text")}
                        link={"acc/IAS_28.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item16.code")}
                        text={t("pdfAcc.item16.text")}
                        link={"acc/IAS_29.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item17.code")}
                        text={t("pdfAcc.item17.text")}
                        link={"acc/IAS_32.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item18.code")}
                        text={t("pdfAcc.item18.text")}
                        link={"acc/IAS_33.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item19.code")}
                        text={t("pdfAcc.item19.text")}
                        link={"acc/IAS_34.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item20.code")}
                        text={t("pdfAcc.item20.text")}
                        link={"acc/IAS_36.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item21.code")}
                        text={t("pdfAcc.item21.text")}
                        link={"acc/IAS_37.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item22.code")}
                        text={t("pdfAcc.item22.text")}
                        link={"acc/IAS_38.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item23.code")}
                        text={t("pdfAcc.item23.text")}
                        link={"acc/IAS_39.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item24.code")}
                        text={t("pdfAcc.item24.text")}
                        link={"acc/IAS_40.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfAcc.item25.code")}
                        text={t("pdfAcc.item25.text")}
                        link={"acc/IAS_41.pdf"}
                    />
                </div>
                <div className={s.financial}>
                    <h3>{t("pdfFin.title")}</h3>
                    <DownloadBtn
                        code={t("pdfFin.item1.code")}
                        text={t("pdfFin.item1.text")}
                        link={"fin/IFRS_1.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item2.code")}
                        text={t("pdfFin.item2.text")}
                        link={"fin/IFRS_2.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item3.code")}
                        text={t("pdfFin.item3.text")}
                        link={"fin/IFRS_3.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item4.code")}
                        text={t("pdfFin.item4.text")}
                        link={"fin/IFRS_5.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item5.code")}
                        text={t("pdfFin.item5.text")}
                        link={"fin/IFRS_6.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item6.code")}
                        text={t("pdfFin.item6.text")}
                        link={"fin/IFRS_7.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item7.code")}
                        text={t("pdfFin.item7.text")}
                        link={"fin/IFRS_8.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item8.code")}
                        text={t("pdfFin.item8.text")}
                        link={"fin/IFRS_9.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item9.code")}
                        text={t("pdfFin.item9.text")}
                        link={"fin/IFRS_10.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item10.code")}
                        text={t("pdfFin.item10.text")}
                        link={"fin/IFRS_11.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item11.code")}
                        text={t("pdfFin.item11.text")}
                        link={"fin/IFRS_12.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item12.code")}
                        text={t("pdfFin.item12.text")}
                        link={"fin/IFRS_13.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item13.code")}
                        text={t("pdfFin.item13.text")}
                        link={"fin/IFRS_14.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item14.code")}
                        text={t("pdfFin.item14.text")}
                        link={"fin/IFRS_15.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item15.code")}
                        text={t("pdfFin.item15.text")}
                        link={"fin/IFRS_16.pdf"}
                    />
                    <DownloadBtn
                        code={t("pdfFin.item16.code")}
                        text={t("pdfFin.item16.text")}
                        link={"fin/IFRS_17.pdf"}
                    />
                </div>
            </div>
        </section>
    );
}

export default Standards;